// Mapa único nombre → logo SVG oficial (react-icons/si, tree-shaken).
// Lo consumen la marquesina (StackLoop) y las etiquetas estáticas (TechTags).
// Tecnología sin logo en simple-icons (Clarity, DOE, OverTheWire): texto.
import type { IconType } from "react-icons";
import {
  SiNextdotjs,
  SiTypescript,
  SiReact,
  SiAstro,
  SiTailwindcss,
  SiShadcnui,
  SiSupabase,
  SiPostgresql,
  SiCloudflare,
  SiVercel,
  SiCoolify,
  SiGit,
  SiN8N,
  SiGoogleanalytics,
  SiMeta,
  SiPython,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiPandas,
  SiOpenjdk,
  SiSpring,
  SiFastapi,
  SiNodedotjs,
  SiAngular,
  SiMysql,
  SiMqtt,
  SiArduino,
  SiHackthebox,
} from "react-icons/si";

// Partial: no toda etiqueta tiene logo (ej. Microsoft Clarity). Sin esto,
// TypeScript cree que la búsqueda siempre devuelve un ícono y el chequeo
// `Icon ? ...` de TechTags falla con ts(2774).
export const TECH_ICONS: Partial<Record<string, IconType>> = {
  "Next.js": SiNextdotjs,
  TypeScript: SiTypescript,
  React: SiReact,
  Astro: SiAstro,
  Tailwind: SiTailwindcss,
  "shadcn/ui": SiShadcnui,
  Supabase: SiSupabase,
  PostgreSQL: SiPostgresql,
  "Cloudflare Functions": SiCloudflare,
  "Cloudflare Pages": SiCloudflare,
  Vercel: SiVercel,
  Coolify: SiCoolify,
  Git: SiGit,
  n8n: SiN8N,
  GA4: SiGoogleanalytics,
  "Meta Pixel": SiMeta,
  Python: SiPython,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "scikit-learn": SiScikitlearn,
  Pandas: SiPandas,
  Java: SiOpenjdk,
  "Spring Boot": SiSpring,
  FastAPI: SiFastapi,
  "Node.js": SiNodedotjs,
  Angular: SiAngular,
  MySQL: SiMysql,
  MQTT: SiMqtt,
  Arduino: SiArduino,
  "Hack The Box": SiHackthebox,
};
